name: offline_cinematic_player
description: Premium offline-first local music player reconstructed from a reference recording.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  just_audio: ^0.10.6
  just_audio_background: ^0.0.1-beta.17
  on_audio_query: ^2.9.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  palette_generator: ^0.3.3+7
  intl: ^0.19.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo/
